#POST http://localhost:8080/tags/add-post-tag
#Content-Type: application/json
#
#{
#  "tagName": "widokowy",
#  "tagDescription": "szlaki dla turystów chcących podziwiać faunę i florę",
#  "tagTrailIds": [4, 5, 7]
#}

POST http://localhost:8080/tags/update-post-tag/3
Content-Type: application/json

{
   "tagName": "dla psów",
   "tagDescription": "szlak odpowiedni dla psów i innych zwierząt",
   "tagTrailIds": [7, 5]
}