POST http://localhost:8080/tags/add-post
Content-Type: application/json

{
  "tagName": "widokowy",
  "tagDescription": "szlaki dla turystów chcących podziwiać faunę i floręszlaki dla turystów chcących podziwiać faunę i floręszlaki dla turystów chcących podziwiać faunę i floręszlaki dla turystów chcących podziwiać faunę i floręszlaki dla turystów chcących podziwiać faunę i floręszlaki dla turystów chcących podziwiać faunę i floręszlaki dla turystów chcących podziwiać faunę i floręszlaki dla turystów chcących podziwiać faunę i floręszlaki dla turystów chcących podziwiać faunę i floręszlaki dla turystów chcących podziwiać faunę i floręszlaki dla turystów chcących podziwiać faunę i floręszlaki dla turystów chcących podziwiać faunę i florę",
  "tagTrailIds": []
}

//#POST http://localhost:8080/tags/update-post/3
//#Content-Type: application/json
//#
//#{
//#   "tagName": "dla psów",
//#   "tagDescription": "szlak odpowiedni dla psów i innych zwierząt",
//#   "tagTrailIds": []
//#}